server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: campus-career-platform
  datasource:
    driver-class-name: ${ccpd.datasource.driver-class-name}
    url: jdbc:mysql://${ccpd.datasource.host}:${ccpd.datasource.port}/${ccpd.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${ccpd.datasource.username}
    password: ${ccpd.datasource.password}
  redis:
    host: ${ccpd.redis.host}
    port: ${ccpd.redis.port}
    password: ${ccpd.redis.password}
    database: ${ccpd.redis.database}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
    date-format: "yyyy-MM-dd HH:mm:ss"
  jwt:
    secret-key: ${ccpd.jwt.secret-key}
    ttl: ${ccpd.jwt.ttl}
    # 设置前端传递过来的令牌名称
    token-name: ${ccpd.jwt.token-name}
#  cloud:
#    sentinel:
#      transport:
#        port: 8179
#        dashboard: localhost:8080 #配置Sentinel dashboard地址

mybatis-plus:
  type-aliases-package: com.campus.career.infra.persistence.mysql.entity # 别名扫描包

logging:
  level:
    com:
      ato:
        mapper: debug
        service: info
        controller: info

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.campus.career.infra.persistence.mysql.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true